using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WpfApp1.json
{
    public class TurbocutLangugageModel
    {
        public string axis00_zpc_çikiş_profil_çikartma_z { get; set; }
        public string axis01_zps_giriş_profil_sürme_z { get; set; }
        public string axis02_zgx_giriş_gripper_konumlama_x { get; set; }
        public string axis03_zgy_giriş_gripper_konumlama_y { get; set; }
        public string axis04_zgr_giriş_gripper_döndürme_r { get; set; }
        public string axis05_xpk_giriş_profil_konumlama_x { get; set; }
        public string axis06_zfo_freze_öncesi_sikma_z { get; set; }
        public string axis07_yfo_freze_öncesi_sikma_y { get; set; }
        public string axis08_xfo_freze_öncesi_sikma_x_iptal { get; set; }
        public string axis09_yft_freze_takimlar_y { get; set; }
        public string axis10_xft_freze_takimlar_x { get; set; }
        public string axis11_yfa_freze_takimgrup_ay { get; set; }
        public string axis12_yfb_freze_takimgrup_by { get; set; }
        public string axis13_zfs_freze_sonrasi_sikma_z { get; set; }
        public string axis14_yfs_freze_sonrasi_sikma_y { get; set; }
        public string axis15_xfs_freze_sonrasi_sikma_x_iptal { get; set; }
        public string axis16_ytu_üst_testere_y { get; set; }
        public string axis17_xtu_üst_testere_x { get; set; }
        public string axis18_rtu_üst_testere_r { get; set; }
        public string axis19_yta_alt_testere_y { get; set; }
        public string axis20_xta_alt_testere_x { get; set; }
        public string axis21_rta_alt_testere_r { get; set; }
        public string axis22_zts_testere_sonrasi_sikma_z { get; set; }
        public string axis23_yts_testere_sonrasi_sikma_y { get; set; }
        public string axis24_xts_testere_sonrasi_sikma_x_iptal { get; set; }
        public string plc_bağlantisi_yapilamadi { get; set; }
        public string başariyla_kaydedildi { get; set; }
        public string sifirlama_aparat_gen { get; set; }
        public string sifirlama_aparat_yük { get; set; }
        public string kol_x_0 { get; set; }
        public string kol_y_sifir { get; set; }
        public string kol_lazer_mes { get; set; }
        public string kol_testere_45_mes { get; set; }
        public string lazer_freze_mes { get; set; }
        public string lazer_test_mes { get; set; }
        public string kol_freze_once_poz { get; set; }
        public string kol_freze_sonra_poz { get; set; }
        public string kol_test_once_poz { get; set; }
        public string kol_test_sonra_poz { get; set; }
        public string kol_parça_birak_mes { get; set; }
        public string test_fire_45135 { get; set; }
        public string test_dire_90135 { get; set; }
        public string test_fire_4590 { get; set; }
        public string son_parça_90_kes { get; set; }
        public string son_parça_dilimleme { get; set; }
        public string max_çikarma_uzunluk { get; set; }
        public string freze_sikma_basinç { get; set; }
        public string test_sikma_basinç { get; set; }
        public string yağlama_çalişma_sn { get; set; }
        public string yağlama_bekleme_dak { get; set; }
        public string freze_bekleme_x { get; set; }
        public string freze_bekleme_y { get; set; }
        public string test_kalinlik_üst { get; set; }
        public string test_kalinlik_alt { get; set; }
        public string dayama_alt_testere_mesafe_135 { get; set; }
        public string dayama_alt_testere_mesafe { get; set; }
        public string alt_test_fire_45135 { get; set; }
        public string alt_test_fire_90135 { get; set; }
        public string alt_test_fire_4590 { get; set; }
        public string ilk_parça_ilave_mm { get; set; }
        public string uç_temizleme_mm { get; set; }
        public string alt_testere_45_kal { get; set; }
        public string masa_yan_sikma_poz_1 { get; set; }
        public string masa_yan_sikma_poz_2 { get; set; }
        public string masa_yan_sikma_poz_3 { get; set; }
        public string masa_yan_sikma_poz_4 { get; set; }
        public string masa_yan_sikma_poz_5 { get; set; }
        public string masa_yan_sikma_poz_6 { get; set; }
        public string masa_yan_sikma_poz_7 { get; set; }
        public string masa_yan_sikma_poz_8 { get; set; }
        public string masa_yan_sikma_poz_9 { get; set; }
        public string masa_yan_sikma_poz_10 { get; set; }
        public string masa_yan_sikma_poz_11 { get; set; }
        public string masa_yan_sikma_poz_12 { get; set; }
        public string masa_yan_sikma_poz_13 { get; set; }
        public string frezeon1 { get; set; }
        public string frezeon2 { get; set; }
        public string frezeon3 { get; set; }
        public string frezeon4 { get; set; }
        public string frezeon5 { get; set; }
        public string frezeon6 { get; set; }
        public string frezeon7 { get; set; }
        public string frezeon8 { get; set; }
        public string frezeon9 { get; set; }
        public string frezeon10 { get; set; }
        public string frezeon11 { get; set; }
        public string frezeon12 { get; set; }
        public string testereust { get; set; }
        public string testerealt { get; set; }
        public string frezemotor1 { get; set; }
        public string frezemotor2 { get; set; }
        public string frezemotor3 { get; set; }
        public string frezemotor4 { get; set; }
        public string frezemotor5 { get; set; }
        public string frezemotor6 { get; set; }
        public string frezemotor7 { get; set; }
        public string frezemotor8 { get; set; }
        public string frezemotor9 { get; set; }
        public string frezemotor10 { get; set; }
        public string frezemotor11 { get; set; }
        public string frezemotor12 { get; set; }
        public string testeremotorust { get; set; }
        public string testeremotoralt { get; set; }
        public string giriş_konveyör_motoru { get; set; }
        public string giriş_konveyör_motoru_geri { get; set; }
        public string talaş_konveyörü { get; set; }
        public string yağlama { get; set; }
        public string yağlama_2 { get; set; }
        public string yağlama_3 { get; set; }
        public string çikiş_masasi { get; set; }
        public string freze_oncesi_ust_tabla_yukari_valfi { get; set; }
        public string freze_oncesi_ust_baski_asagi_valfi { get; set; }
        public string freze_oncesi_alt_baski_yukari_valfi { get; set; }
        public string freze_oncesi_arka_yan_baski_siper_valfi { get; set; }
        public string freze_oncesi_on_yan_baski_rulo_valfi { get; set; }
        public string freze_sonrasi_ust_tabla_yukari_valfi { get; set; }
        public string freze_sonrasi_ust_baski_asagi_valfi { get; set; }
        public string freze_sonrasi_alt_baski_yukari_valfi { get; set; }
        public string freze_sonrasi_arka_yan_baski_siper_valfi { get; set; }
        public string freze_sonrasi_on_yan_baski_siper_valfi { get; set; }
        public string freze_sonrasi_on_yan_baski_rulo_valfi { get; set; }
        public string testere_sonrasi_on_grup_sabitleme_valfi { get; set; }
        public string testere_sonrasi_on_grup_sabitleme_kilit_ { get; set; }
        public string testere_sonrasi_on_grup_yan_baski_siper_ { get; set; }
        public string testere_sonrasi_on_grup_yan_baski_rulo_v { get; set; }
        public string testere_sonrasi_ust_tabla_yukari_valfi { get; set; }
        public string testere_sonrasi_ust_baski_asagi_valfi { get; set; }
        public string testere_sonrasi_alt_baski_yukari_valfi { get; set; }
        public string testere_sonrasi_arka_yan_baski_siper_val { get; set; }
        public string cikis_yukari_itme_valfi { get; set; }
        public string cikis_ileri_itme_valfi { get; set; }
        public string giris_yan_baski_grup1_ileri_valfi { get; set; }
        public string giris_yan_baski_grup2_ileri_valfi { get; set; }
        public string giris_yan_baski_grup3_ileri_valfi { get; set; }
        public string giris_yan_baski_grup4_ileri_valfi { get; set; }
        public string giris_yan_baski_grup5_ileri_valfi { get; set; }
        public string giris_yan_baski_grup6_ileri_valfi { get; set; }
        public string giris_yan_baski_grup1_kisa_yukari_valfi { get; set; }
        public string giris_yan_baski_grup1_uzun_yukari_valfi { get; set; }
        public string giris_yan_baski_grup2_kisa_yukari_valfi { get; set; }
        public string giris_yan_baski_grup2_uzun_yukari_valfi { get; set; }
        public string giris_yan_baski_grup3_kisa_yukari_valfi { get; set; }
        public string giris_yan_baski_grup3_uzun_yukari_valfi { get; set; }
        public string giris_yan_baski_grup4_kisa_yukari_valfi { get; set; }
        public string giris_yan_baski_grup4_uzun_yukari_valfi { get; set; }
        public string giris_yan_baski_grup5_kisa_yukari_valfi { get; set; }
        public string giris_yan_baski_grup5_uzun_yukari_valfi { get; set; }
        public string giris_yan_baski_grup6_kisa_yukari_valfi { get; set; }
        public string giris_yan_baski_grup6_uzun_yukari_valfi { get; set; }
        public string giris_tork_dayama_valfi { get; set; }
        public string giris_gripper_kapat_valfi { get; set; }
        public string giris_profil_dikme_1_yukari_valfi { get; set; }
        public string giris_profil_dikme_2_yukari_valfi { get; set; }
        public string giris_profil_dikme_3_yukari_valfi { get; set; }
        public string giris_profil_dikme_4_yukari_valfi { get; set; }
        public string giris_ust_baski_1_ileri_valfi { get; set; }
        public string giris_ust_baski_2_ileri_valfi { get; set; }
        public string giris_ust_baski_3_ileri_valfi { get; set; }
        public string giris_ust_baski_4_ileri_valfi { get; set; }
        public string giris_ust_baskilar_yukari_valfi { get; set; }
        public string alarm00 { get; set; }
        public string alarm01_plc_hatasi { get; set; }
        public string alarm02_ethernet_ip_hatasi { get; set; }
        public string alarm03_ethercat_hatasi { get; set; }
        public string alarm04_motion_control_hatasi { get; set; }
        public string alarm05_io_bus_hatasi { get; set; }
        public string alarm06_giriş_işik_bariyeri_ihlali { get; set; }
        public string alarm07_giriş_acil_stop_basili { get; set; }
        public string alarm08_kumanda_paneli_acil_stop_basili { get; set; }
        public string alarm09_kapi_açik_kontrol_ediniz { get; set; }
        public string alarm10_hava_basinci_yetersiz_kontrol_ed { get; set; }
        public string alarm11_yağlama_tanki_seviyesi_düşük { get; set; }
        public string alarm12_freze_takimlar_inverter_1_hatada { get; set; }
        public string alarm13_freze_takimlar_inverter_2_hatada { get; set; }
        public string alarm14_üst_testere_inverter_hatada { get; set; }
        public string alarm15_alt_testere_inverter_hatada { get; set; }
        public string alarm16_giriş_konveyör_termik_atti { get; set; }
        public string alarm17_üst_testere_45_termik_atti { get; set; }
        public string alarm18_üst_testere_termik_atti_90 { get; set; }
        public string alarm19_alt_testere_termik_atti_135 { get; set; }
        public string alarm20_talaş_konveyör_termik_atti { get; set; }
        public string alarm21_çikiş_konveyör_termik_atti { get; set; }
        public string alarm22_kabin_girisi_hizalama_profili_ka { get; set; }
        public string alarm23 { get; set; }
        public string alarm24_axis_00_zpc_ekseni_servo_sürücü_ { get; set; }
        public string alarm25_axis_00_zpc_pozitif_limit_sw_gör { get; set; }
        public string alarm26_axis_00_zpc_negatif_limit_sw_gör { get; set; }
        public string alarm27_axis_00_zpc_ekseni_pozisyon_limi { get; set; }
        public string alarm28_axis_01_zps_ekseni_servo_sürücü_ { get; set; }
        public string alarm29_axis_01_zps_pozitif_limit_sw_gör { get; set; }
        public string alarm30_axis_01_zps_negatif_limit_sw_gör { get; set; }
        public string alarm31_axis_01_zps_ekseni_pozisyon_limi { get; set; }
        public string alarm32_axis_02_zgx_ekseni_servo_sürücü_ { get; set; }
        public string alarm33_axis_02_zgx_pozitif_limit_sw_gör { get; set; }
        public string alarm34_axis_02_zgx_negatif_limit_sw_gör { get; set; }
        public string alarm35_axis_02_zgx_ekseni_pozisyon_limi { get; set; }
        public string alarm36_axis_03_zgy_ekseni_servo_sürücü_ { get; set; }
        public string alarm37_axis_03_zgy_pozitif_limit_sw_gör { get; set; }
        public string alarm38_axis_03_zgy_negatif_limit_sw_gör { get; set; }
        public string alarm39_axis_03_zgy_ekseni_pozisyon_limi { get; set; }
        public string alarm40_axis_04_zgr_ekseni_servo_sürücü_ { get; set; }
        public string alarm41_axis_04_zgr_pozitif_limit_sw_gör { get; set; }
        public string alarm42_axis_04_zgr_negatif_limit_sw_gör { get; set; }
        public string alarm43_axis_04_zgr_ekseni_pozisyon_limi { get; set; }
        public string alarm44_axis_05_xpk_ekseni_servo_sürücü_ { get; set; }
        public string alarm45_axis_05_xpk_pozitif_limit_sw_gör { get; set; }
        public string alarm46_axis_05_xpk_negatif_limit_sw_gör { get; set; }
        public string alarm47_axis_05_xpk_ekseni_pozisyon_limi { get; set; }
        public string alarm48_axis_06_zfo_ekseni_servo_sürücü_ { get; set; }
        public string alarm49_axis_06_zfo_pozitif_limit_sw_gör { get; set; }
        public string alarm50_axis_06_zfo_negatif_limit_sw_gör { get; set; }
        public string alarm51_axis_06_zfo_ekseni_pozisyon_limi { get; set; }
        public string alarm52_axis_07_yfo_ekseni_servo_sürücü_ { get; set; }
        public string alarm53_axis_07_yfo_pozitif_limit_sw_gör { get; set; }
        public string alarm54_axis_07_yfo_negatif_limit_sw_gör { get; set; }
        public string alarm55_axis_07_yfo_ekseni_pozisyon_limi { get; set; }
        public string alarm56_axis_08_xfo_eksen_servo_sürücü_h { get; set; }
        public string alarm57_axis_08_xfo_pozitif_limit_sw_gör { get; set; }
        public string alarm58_axis_08_xfo_negatif_limit_sw_gör { get; set; }
        public string alarm59_axis_08_xfo_ekseni_pozisyon_limi { get; set; }
        public string alarm60_axis_09_yft_ekseni_servo_sürücü_ { get; set; }
        public string alarm61_axis_09_yft_pozitif_limit_sw_gör { get; set; }
        public string alarm62_axis_09_yft_negatif_limit_sw_gör { get; set; }
        public string alarm63_axis_09_yft_ekseni_pozisyon_limi { get; set; }
        public string alarm64_axis_10_xft_ekseni_servo_sürücü_ { get; set; }
        public string alarm65_axis_10_xft_pozitif_limit_sw_gör { get; set; }
        public string alarm66_axis_10_xft_negatif_limit_sw_gör { get; set; }
        public string alarm67_axis_10_xft_ekseni_pozisyon_limi { get; set; }
        public string alarm68_axis_11_yfa_ekseni_servo_sürücü_ { get; set; }
        public string alarm69_axis_11_yfa_pozitif_limit_sw_gör { get; set; }
        public string alarm70_axis_11_yfa_negatif_limit_sw_gör { get; set; }
        public string alarm71_axis_11_yfa_ekseni_pozisyon_limi { get; set; }
        public string alarm72_axis_12_yfb_ekseni_servo_sürücü_ { get; set; }
        public string alarm73_axis_12_yfb_pozitif_limit_sw_gör { get; set; }
        public string alarm74_axis_12_yfb_negatif_limit_sw_gör { get; set; }
        public string alarm75_axis_12_yfb_ekseni_pozisyon_limi { get; set; }
        public string alarm76_axis_13_zfs_ekseni_servo_sürücü_ { get; set; }
        public string alarm77_axis_13_zfs_pozitif_limit_sw_gör { get; set; }
        public string alarm78_axis_13_zfs_negatif_limit_sw_gör { get; set; }
        public string alarm79_axis_13_zfs_ekseni_pozisyon_limi { get; set; }
        public string alarm80_axis_14_yfs_ekseni_servo_sürücü_ { get; set; }
        public string alarm81_axis_14_yfs_pozitif_limit_sw_gör { get; set; }
        public string alarm82_axis_14_yfs_negatif_limit_sw_gör { get; set; }
        public string alarm83_axis_14_yfs_ekseni_pozisyon_limi { get; set; }
        public string alarm84_axis_15_xfs_ekseni_servo_sürücü_ { get; set; }
        public string alarm85_axis_15_xfs_pozitif_limit_sw_gör { get; set; }
        public string alarm86_axis_15_xfs_negatif_limit_sw_gör { get; set; }
        public string alarm87_axis_15_xfs_ekseni_pozisyon_limi { get; set; }
        public string alarm88_axis_16_ytu_ekseni_servo_sürücü_ { get; set; }
        public string alarm89_axis_16_ytu_pozitif_limit_sw_gör { get; set; }
        public string alarm90_axis_16_ytu_negatif_limit_sw_gör { get; set; }
        public string alarm91_axis_16_ytu_ekseni_pozisyon_limi { get; set; }
        public string alarm92_axis_17_xtu_ekseni_servo_sürücü_ { get; set; }
        public string alarm93_axis_17_xtu_pozitif_limit_sw_gör { get; set; }
        public string alarm94_axis_17_xtu_negatif_limit_sw_gör { get; set; }
        public string alarm95_axis_17_xtu_ekseni_pozisyon_limi { get; set; }
        public string alarm96_axis_18_rtu_ekseni_servo_sürücü_ { get; set; }
        public string alarm97_axis_18_rtu_pozitif_limit_sw_gör { get; set; }
        public string alarm98_axis_18_rtu_negatif_limit_sw_gör { get; set; }
        public string alarm99_axis_18_rtu_ekseni_pozisyon_limi { get; set; }
        public string alarm100_axis_19_yta_ekseni_servo_sürücü { get; set; }
        public string alarm101_axis_19_yta_pozitif_limit_sw_gö { get; set; }
        public string alarm102_axis_19_yta_negatif_limit_sw_gö { get; set; }
        public string alarm103_axis_19_yta_ekseni_pozisyon_lim { get; set; }
        public string alarm104_axis_20_xta_ekseni_servo_sürücü { get; set; }
        public string alarm105_axis_20_xta_pozitif_limit_sw_gö { get; set; }
        public string alarm106_axis_20_xta_negatif_limit_sw_gö { get; set; }
        public string alarm107_axis_20_xta_ekseni_pozisyon_lim { get; set; }
        public string alarm108_axis_21_rta_ekseni_servo_sürücü { get; set; }
        public string alarm109_axis_21_rta_pozitif_limit_sw_gö { get; set; }
        public string alarm110_axis_21_rta_negatif_limit_sw_gö { get; set; }
        public string alarm111_axis_21_rta_ekseni_pozisyon_lim { get; set; }
        public string alarm112_axis_22_zts_ekseni_servo_sürücü { get; set; }
        public string alarm113_axis_22_zts_pozitif_limit_sw_gö { get; set; }
        public string alarm114_axis_22_zts_negatif_limit_sw_gö { get; set; }
        public string alarm115_axis_22_zts_ekseni_pozisyon_lim { get; set; }
        public string alarm116_axis_23_yts_ekseni_servo_sürücü { get; set; }
        public string alarm117_axis_23_yts_pozitif_limit_sw_gö { get; set; }
        public string alarm118_axis_23_yts_negatif_limit_sw_gö { get; set; }
        public string alarm119_axis_23_yts_ekseni_pozisyon_lim { get; set; }
        public string alarm120_axis_24_xts_ekseni_servo_sürücü { get; set; }
        public string alarm121_axis_24_xts_pozitif_limit_sw_gö { get; set; }
        public string alarm122_axis_24_xts_negatif_limit_sw_gö { get; set; }
        public string alarm123_axis_24_xts_ekseni_pozisyon_lim { get; set; }
        public string alarm124 { get; set; }
        public string alarm125 { get; set; }
        public string alarm126 { get; set; }
        public string alarm127 { get; set; }
        public string alarm128_giriş_yan_baski_grup_1_ileri_ha { get; set; }
        public string alarm129_giriş_yan_baski_grup_2_ileri_ha { get; set; }
        public string alarm130_giriş_yan_baski_grup_3_ileri_ha { get; set; }
        public string alarm131_giriş_yan_baski_grup_4_ileri_ha { get; set; }
        public string alarm132_giriş_yan_baski_grup_5_ileri_ha { get; set; }
        public string alarm133_giriş_yan_baski_grup_6_ileri_ha { get; set; }
        public string alarm134_giriş_yan_baski_grup_1_kisa_yuk { get; set; }
        public string alarm135_giriş_yan_baski_grup_1_uzun_yuk { get; set; }
        public string alarm136_giriş_yan_baski_grup_2_kisa_yuk { get; set; }
        public string alarm137_giriş_yan_baski_grup_2_uzun_yuk { get; set; }
        public string alarm138_giriş_yan_baski_grup_3_kisa_yuk { get; set; }
        public string alarm139_giriş_yan_baski_grup_3_uzun_yuk { get; set; }
        public string alarm140_giriş_yan_baski_grup_4_kisa_yuk { get; set; }
        public string alarm141_giriş_yan_baski_grup_4_uzun_yuk { get; set; }
        public string alarm142_giriş_yan_baski_grup_5_kisa_yuk { get; set; }
        public string alarm143_giriş_yan_baski_grup_5_uzun_yuk { get; set; }
        public string alarm144_giriş_yan_baski_grup_6_kisa_yuk { get; set; }
        public string alarm145_giriş_yan_baski_grup_6_uzun_yuk { get; set; }
        public string alarm146_giriş_profil_dikme_1_hatasi { get; set; }
        public string alarm147_giriş_profil_dikme_2_hatasi { get; set; }
        public string alarm148_giriş_profil_dikme_3_hatasi { get; set; }
        public string alarm149_giriş_profil_dikme_4_hatasi { get; set; }
        public string alarm150_giriş_üst_baski_1_ileri_hatasi { get; set; }
        public string alarm151_giriş_üst_baski_2_ileri_hatasi { get; set; }
        public string alarm152_giriş_üst_baski_3_ileri_hatasi { get; set; }
        public string alarm153_giriş_üst_baski_4_ileri_hatasi { get; set; }
        public string alarm154_giriş_üst_baskilar_yukari_hatas { get; set; }
        public string alarm155 { get; set; }
        public string alarm156 { get; set; }
        public string alarm157 { get; set; }
        public string alarm158 { get; set; }
        public string alarm159 { get; set; }
        public string alarm160_giriş_üst_baski_1_hatasi { get; set; }
        public string alarm161_giriş_yan_sikma_hatasi { get; set; }
        public string alarm162_giriş_üst_sikma_döndürme_1_hata { get; set; }
        public string alarm163_giriş_üst_sikma_döndürme_2_hata { get; set; }
        public string alarm164_giriş_üst_sikma_döndürme_3_hata { get; set; }
        public string alarm165_giriş_yan_sikma_yukariaşaği_hat { get; set; }
        public string alarm166_giriş_yan_sikma_boşaltma_hatasi { get; set; }
        public string alarm167_giriş_gaga_sikma_hatasi { get; set; }
        public string alarm168_giriş_tork_dayama_hatasi { get; set; }
        public string alarm169_giriş_tork_dayama_sensör_hatasi { get; set; }
        public string alarm170_giriş_üst_baski_2_hatasi { get; set; }
        public string alarm171_giriş_üst_baski_3_hatasi { get; set; }
        public string alarm172 { get; set; }
        public string alarm173 { get; set; }
        public string alarm174 { get; set; }
        public string alarm175 { get; set; }
        public string alarm176_freze_tool_1_hatasi { get; set; }
        public string alarm177_freze_tool_2_hatasi { get; set; }
        public string alarm178_freze_tool_3_hatasi { get; set; }
        public string alarm179_freze_tool_4_hatasi { get; set; }
        public string alarm180_freze_tool_5_hatasi { get; set; }
        public string alarm181_freze_tool_6_hatasi { get; set; }
        public string alarm182_freze_tool_7_hatasi { get; set; }
        public string alarm183_freze_tool_8_hatasi { get; set; }
        public string alarm184_freze_tool_9_hatasi { get; set; }
        public string alarm185_freze_tool_10_hatasi { get; set; }
        public string alarm186_freze_tool_11_hatasi { get; set; }
        public string alarm187_freze_tool_12_hatasi { get; set; }
        public string alarm188 { get; set; }
        public string alarm189 { get; set; }
        public string alarm190 { get; set; }
        public string alarm191 { get; set; }
        public string alarm192_freze_öncesi_üst_sikma_hatasi { get; set; }
        public string alarm193_freze_öncesi_yan_sikma_hatasi { get; set; }
        public string alarm194_freze_öncesi_conta_baski_hatasi { get; set; }
        public string alarm195 { get; set; }
        public string alarm196 { get; set; }
        public string alarm197 { get; set; }
        public string alarm198 { get; set; }
        public string alarm199 { get; set; }
        public string alarm200_freze_sonrasi_üst_sikma_hatasi { get; set; }
        public string alarm201_freze_sonrasi_yan_sikma_hatasi { get; set; }
        public string alarm202_freze_sonrasi_conta_baski_hatas { get; set; }
        public string alamr203 { get; set; }
        public string alarm204 { get; set; }
        public string alarm205 { get; set; }
        public string alarm206 { get; set; }
        public string alarm207 { get; set; }
        public string alarm208_testere_öncesi_üst_sikma_hatasi { get; set; }
        public string alarm209_testere_öncesi_üst_yan_sikma_ha { get; set; }
        public string alarm210_testere_öncesi_alt_yan_sikma_ha { get; set; }
        public string alarm211_testere_öncesi_conta_baski_hata { get; set; }
        public string alarm212_testere_öncesi_damlalikli_baski { get; set; }
        public string alarm213 { get; set; }
        public string alarm214 { get; set; }
        public string alarm215 { get; set; }
        public string alarm216_testere_sonrasi_üst_sikma_hatas { get; set; }
        public string alarm217_testere_sonrasi_üst_yan_sikma_h { get; set; }
        public string alarm218_testere_sonrasi_alt_yan_sikma_h { get; set; }
        public string alarm219_testere_sonrasi_conta_baski_hat { get; set; }
        public string alarm220_testere_sonrasi_damlalikli_bask { get; set; }
        public string alarm221 { get; set; }
        public string alarm222 { get; set; }
        public string alarm223 { get; set; }
        public string alarm224_freze_öncesi_üst_tabla_hatasi { get; set; }
        public string alarm225_freze_öncesi_üst_baski_hatasi { get; set; }
        public string alarm226_freze_öncesi_alt_baski_hatasi { get; set; }
        public string alarm227_freze_öncesi_arka_yan_baski_sip { get; set; }
        public string alarm228_freze_öncesi_ön_yan_baski_rulol { get; set; }
        public string alarm229 { get; set; }
        public string alarm230 { get; set; }
        public string alarm231 { get; set; }
        public string alarm232_freze_sonrasi_üst_tabla_hatasi { get; set; }
        public string alarm233_freze_sonrasi_üst_baski_hatasi { get; set; }
        public string alarm234_freze_sonrasi_alt_baski_hatasi { get; set; }
        public string alarm235_freze_sonrasi_arka_yan_baski_si { get; set; }
        public string alarm236_freze_sonrasi_ön_yan_baski_sipe { get; set; }
        public string alarm237_freze_sonrasi_ön_yan_baski_rulo { get; set; }
        public string alarm238_giris_arka_dayama_1_sensor_hata { get; set; }
        public string alarm239_giris_arka_dayama_2_sensor_hata { get; set; }
        public string alarm240_testere_sonrasi_ön_grup_sabitle { get; set; }
        public string alarm241_testere_sonrasi_ön_grup_sabitle { get; set; }
        public string alarm242_testere_sonrasi_ön_grup_ön_yan_ { get; set; }
        public string alarm243_testere_sonrasi_ön_grup_ön_yan_ { get; set; }
        public string alarm244 { get; set; }
        public string alarm245 { get; set; }
        public string alarm246 { get; set; }
        public string alarm247 { get; set; }
        public string alarm248_testere_sonrasi_üst_tabla_hatas { get; set; }
        public string alarm249_testere_sonrasi_üst_baski_hatas { get; set; }
        public string alarm250_testere_sonrasi_alt_baski_hatas { get; set; }
        public string alarm251_testere_sonrasi_arka_yan_baski_ { get; set; }
        public string alarm252 { get; set; }
        public string alarm253 { get; set; }
        public string alarm254 { get; set; }
        public string alarm255 { get; set; }
        public string alarm256_üst_45_testere_piston_hatasi { get; set; }
        public string alarm257_alt_135_testere_piston_hatasi { get; set; }
        public string alarm258_üst_90_testere_piston_hatasi { get; set; }
        public string alarm259 { get; set; }
        public string alarm260 { get; set; }
        public string alarm261 { get; set; }
        public string alarm262 { get; set; }
        public string alarm263 { get; set; }
        public string alarm264_çikiş_profil_tutma_hatasi { get; set; }
        public string alarm265_çikiş_profil_asansör_hatasi { get; set; }
        public string alarm266_çikiş_yukari_itme_hatasi { get; set; }
        public string alarm267_çikiş_ileri_itme_hatasi { get; set; }
        public string alarm268 { get; set; }
        public string alarm269 { get; set; }
        public string alarm270_profil_boyu_yetersiz { get; set; }
        public string alarm271 { get; set; }
        public string alarm272_giriş_profil_algilanmadi_sensör { get; set; }
        public string alarm273_giriş_profil_gripper_tarafindan { get; set; }
        public string alarm274_boy_sifir_veya_küçük_olamaz { get; set; }
        public string alarm275_yükseklik_sifir_veya_küçük_olam { get; set; }
        public string alarm276_en_sifir_veya_küçük_olamaz { get; set; }
        public string alarm277_operasyon_adeti_sifir_veya_küçü { get; set; }
        public string alarm278_freze_işlem_gripper_kol_üzerine { get; set; }
        public string alarm279_testere_kesim_gripper_kol_üzeri { get; set; }
        public string alarm280_profil_sürme_güvenliği_yok { get; set; }
        public string alarm281_giriş_yan_sikma_hatasi_1 { get; set; }
        public string alarm282_giriş_yan_sikma_hatasi_2 { get; set; }
        public string alarm283_giriş_yan_sikma_hatasi_3 { get; set; }
        public string alarm284_giriş_yan_sikma_hatasi_4 { get; set; }
        public string alarm285_giriş_yan_sikma_hatasi_5 { get; set; }
        public string alarm286_giriş_yan_sikma_hatasi_6 { get; set; }
        public string alarm287_giriş_yan_sikma_hatasi_7 { get; set; }
        public string alarm288_giriş_yan_sikma_hatasi_8 { get; set; }
        public string alarm289_giriş_yan_sikma_hatasi_9 { get; set; }
        public string alarm290_giriş_yan_sikma_hatasi_10 { get; set; }
        public string alarm291_giriş_yan_sikma_hatasi_11 { get; set; }
        public string alarm292_giriş_yan_sikma_hatasi_12 { get; set; }
        public string alarm293_giriş_yan_sikma_hatasi_13 { get; set; }
        public string alarm294_giriş_yan_sikma_geri_hatasi { get; set; }
        public string alarm295 { get; set; }
        public string alarm296 { get; set; }
        public string alarm297 { get; set; }
        public string alarm298_giriş_masasi_güvenlik_sensoru { get; set; }
        public string alarm299_çikiş_masasi_güvenlik_sensörü { get; set; }
        public string iş_emri_aç_ozgenc_csv { get; set; }
        public string iş_emri_aç_ozgenc_xml { get; set; }
        public string parça_uzunluğu_hatasi { get; set; }
        public string profil_bulunamadi { get; set; }
        public string bu_boydan_başla { get; set; }
        public string tek_parça_kes { get; set; }
        public string tek_boy_kes { get; set; }
        public string bu_parçadan_başla { get; set; }
        public string yüklü_veriyi_görmek_için_plc_bağlantisi_ { get; set; }
        public string kod { get; set; }
        public string motor { get; set; }
        public string şekil { get; set; }
        public string yaklaşma { get; set; }
        public string derinlik { get; set; }
        public string xpoz { get; set; }
        public string ypoz { get; set; }
        public string zpoz { get; set; }
        public string xofset { get; set; }
        public string yofset { get; set; }
        public string zofset { get; set; }
        public string boş_hiz { get; set; }
        public string giriş_hizi { get; set; }
        public string lineer_hiz { get; set; }
        public string dairesel_hiz { get; set; }
        public string ara_atlama_hizi { get; set; }
        public string operasyon_şekli { get; set; }
        public string boy_listesinde_yeterli_parça_yok { get; set; }
        public string işlemler_bitti { get; set; }
        public string kol_tutma_x_pozisyonu_0_olamaz { get; set; }
        public string kol_tutma_y_pozisyonu_0_olamaz { get; set; }
        public string boş_veri_tablosu { get; set; }
        public string testere_açisi_yanliş { get; set; }
        public string profilmarka { get; set; }
        public string profilstokkod { get; set; }
        public string profilcitakantalix { get; set; }
        public string profilcitakantaliy { get; set; }
        public string profilsizex { get; set; }
        public string profilsizey { get; set; }
        public string desteknoktasix { get; set; }
        public string desteknoktasiy { get; set; }
        public string kaldirmanoktasix { get; set; }
        public string kaldirmanoktasiy { get; set; }
        public string tutucunoktasix { get; set; }
        public string tutucunoktasiy { get; set; }
        public string tutmaacisi { get; set; }
        public string profiltipi { get; set; }
        public string hammadde { get; set; }
        public string damlalikbaski { get; set; }
        public string opsiyon1 { get; set; }
        public string opsiyon2 { get; set; }
        public string opsiyon3 { get; set; }
        public string opsiyon4 { get; set; }
        public string opsiyon5 { get; set; }
        public string kasa { get; set; }
        public string kanat { get; set; }
        public string ortakayit { get; set; }
        public string kapali { get; set; }
        public string açik { get; set; }
        public string kaydet { get; set; }
        public string yeni_profil { get; set; }
        public string genel_data { get; set; }
        public string tablo { get; set; }
        public string gelişmiş { get; set; }
        public string çikiş { get; set; }
        public string prop_03delik { get; set; }
        public string prop_04daire { get; set; }
        public string prop_05dortgen { get; set; }
        public string prop_06kapsül { get; set; }
        public string prop_07çizgi { get; set; }
        public string prop_08barel { get; set; }
        public string prop_09sağ_kertme { get; set; }
        public string prop_10sol_kertme { get; set; }
        public string prop_11çift_delik { get; set; }
        public string prop_12disk_çizgi { get; set; }
        public string lütfen_profil_seçiniz { get; set; }
        public string tüm_alanlar_doldurulmalidir { get; set; }
        public string işlem_numarasi_seçilmelidir { get; set; }
        public string lütfen_profil_yükleyiniz { get; set; }
        public string operasyon_sil { get; set; }
        public string operasyon_kopyala { get; set; }
        public string önce_önemli_verileri_giriniz { get; set; }
        public string yeni_işlem { get; set; }
        public string profil_sil { get; set; }
        public string profil_kopyala { get; set; }
        public string ayni_isimde_profil_mevcut { get; set; }
        public string alt_testere { get; set; }
        public string geçmiş { get; set; }
        public string gelişmiş_freze { get; set; }
        public string gelişmiş_eksen { get; set; }
        public string git { get; set; }
        public string home { get; set; }
        public string işlem_hizi { get; set; }
        public string boş_hiz_1 { get; set; }
        public string kalkiş_rampasi { get; set; }
        public string duruş_rampasi { get; set; }
        public string jerk { get; set; }
        public string max_poz { get; set; }
        public string min_pos { get; set; }
        public string jog_hizi { get; set; }
        public string jog_kalkiş_rampasi { get; set; }
        public string jog_duruş_rampasi { get; set; }
        public string jog_jerk { get; set; }
        public string anlik_pozisyon { get; set; }
        public string manuel_hedef_pozisyon { get; set; }
        public string home_offset { get; set; }
        public string yedek_1 { get; set; }
        public string yedek_2 { get; set; }
        public string prop_2_yaklaşma { get; set; }
        public string giriş_üst_baski_döndürme_1 { get; set; }
        public string giriş_üst_baski_döndürme_2 { get; set; }
        public string giriş_üst_baski_döndürme_3 { get; set; }
        public string giriş_yan_baski_yukariaşaği { get; set; }
        public string giriş_yan_baski_boşaltma { get; set; }
        public string profil_tutma_pensesi { get; set; }
        public string boy_firesi_geri_çekme_siniri { get; set; }
        public string freze_öncesi_üst_yan_baski { get; set; }
        public string freze_öncesi_conta_baski { get; set; }
        public string freze_sonrasi_üst_yan_baski { get; set; }
        public string testere_öncesi_üst_yan_baski { get; set; }
        public string testere_öncesi_alt_yan_baski { get; set; }
        public string testere_öncesi_conta_baski { get; set; }
        public string testere_öncesi_damlalik_baski { get; set; }
        public string testere_sonrasi_üst_baski { get; set; }
        public string çikiş_profil_kaldirma { get; set; }
        public string çikiş_profil_tutma { get; set; }
        public string sifir_aparat_genişlik { get; set; }
        public string sifir_aparat_yükseklik { get; set; }
        public string kol_x_sifir { get; set; }
        public string kol_y_sifir_1 { get; set; }
        public string kol_dayama_mesafe { get; set; }
        public string kol_testere_45_mesafe { get; set; }
        public string dayama_freze_mesafe { get; set; }
        public string dayama_testere_mesafe { get; set; }
        public string kol_freze_öncesi_poz { get; set; }
        public string kol_freze_sonrasi_poz { get; set; }
        public string kol_testere_öncesi_poz { get; set; }
        public string kol_testere_sonrasi_poz { get; set; }
        public string kol_parça_birakma_poz { get; set; }
        public string fire_45135 { get; set; }
        public string fire_90135 { get; set; }
        public string fire_4590 { get; set; }
        public string freze_böl_sikma_basinç { get; set; }
        public string testere_böl_sikma_basinç { get; set; }
        public string yağlama_çalişma_sn_1 { get; set; }
        public string yağlama_bekleme_dak_1 { get; set; }
        public string freze_bekleme_y_1 { get; set; }
        public string freze_bekleme_z { get; set; }
        public string üst_testere_kal { get; set; }
        public string alt_testere_kal { get; set; }
        public string çikarilabilir_profil_uzunluk { get; set; }
        public string ilk_parça_ilave { get; set; }
        public string uç_temizleme_mm_1 { get; set; }
        public string son_parça_90 { get; set; }
        public string dilimleme { get; set; }
        public string üst_test_piston_45 { get; set; }
        public string alt_test_piston_135 { get; set; }
        public string üst_test_piston_90 { get; set; }
        public string üst_test_motor_45 { get; set; }
        public string alt_test_motor_135 { get; set; }
        public string üst_test_motor_90 { get; set; }
        public string üst_testere_45_kal { get; set; }
        public string prop_90_test_135_test_mesafe { get; set; }
        public string prop_90_test_45_test_mesafe { get; set; }
        public string test_sonrasi_alt_yan_baski { get; set; }
        public string test_sonrasi_üst_yan_baski { get; set; }
        public string etiket_yazdir_tüm_parçalar { get; set; }
        public string etiket_yazdir_tek_parça { get; set; }
        public string öncelik_no { get; set; }
        public string acil_stop_basili { get; set; }
        public string profil_sikmalar_valf_hata { get; set; }
        public string kafa1_vidalama_ünitesi_valf_hatasi { get; set; }
        public string kafa2_vidalama_ünitesi_valf_hatasi { get; set; }
        public string home_yaparken_hata { get; set; }
        public string kafa1_x_servo_hata { get; set; }
        public string kafa1_y_servo_hata { get; set; }
        public string kafa2_x_servo_hata { get; set; }
        public string kafa2_y_servo_hata { get; set; }
        public string reserve { get; set; }
        public string ethercat_haberleşme_hatasi { get; set; }
        public string ethernet_haberleşme_hatasi { get; set; }
        public string motion_hatasi { get; set; }
        public string plc_nx_bus_ünite_hatasi { get; set; }
        public string çarpişma_oldu { get; set; }
        public string kafa1_vidalama_motor_piston_valf_hata { get; set; }
        public string kafa2_vidalama_motor_piston_valf_hata { get; set; }
        public string reserve_1 { get; set; }
        public string reserve_2 { get; set; }
        public string reserve_3 { get; set; }
        public string iş_listesi_dolu { get; set; }
        public string gelen_iş_profil_boyu_hatalı { get; set; }
        public string iş_listesinde_hiç_iş_yok { get; set; }
        public string giris_ust_baski_1_yukariasagi { get; set; }
        public string giris_ust_baski_2_yukariasagi { get; set; }
        public string giris_ust_baski_3_yukariasagi { get; set; }
        public string giris_ust_baski_4_yukariasagi { get; set; }
        public string hedef { get; set; }
        public string aktuel { get; set; }
        public string eksen { get; set; }
        public string git_1 { get; set; }
        public string alt_testere_1 { get; set; }
        public string giris_konveyor_ileri { get; set; }
        public string giris_konveyor_geri { get; set; }
        public string talas_konveyor_motoru { get; set; }
        public string yaglama { get; set; }
        public string cikis_konveyor { get; set; }
        public string kabin_giris_ust_baski { get; set; }
        public string kabin_giris_yan_baski_ust { get; set; }
        public string kabin_giris_yan_baski_alt { get; set; }
        public string testere_oncesi_ust_baski { get; set; }
        public string testere_oncesi_alt_dayama { get; set; }
        public string testere_oncesi_damlalikli { get; set; }
        public string testere_sonrasi_yan_sikma_kisa { get; set; }
        public string testere_sonrasi_yan_sikma_uzun { get; set; }
        public string testere_sonrasi_yan_sikma { get; set; }
        public string testere_sonrasi_ust_baski { get; set; }
        public string testere_sonrasi_alt_dayama { get; set; }
        public string testere_sonrasi_damlalikli { get; set; }
        public string vidalama { get; set; }
        public string profiller { get; set; }
        public string makine { get; set; }
        public string cikis { get; set; }
        public string islem_zaten_var_kod { get; set; }
        public string profil { get; set; }
        public string üzerine_yazmak_istiyor_musun { get; set; }
        public string kopyalama_islemi_basarili { get; set; }
        public string koplayama_islemi_iptal_edildi { get; set; }
        public string uzerine_yazma_onayi { get; set; }
        public string x_acc { get; set; }
        public string x_jerk { get; set; }
        public string y_hiz { get; set; }
        public string y_acc { get; set; }
        public string y_jerk { get; set; }
        public string tool_emniyet_mesafesi { get; set; }
        public string kafa_1_min_x_pos { get; set; }
        public string kafa_2_max_pos { get; set; }
        public string profil_sensor_gecikme { get; set; }
        public string profil_sikma_zamani { get; set; }
        public string vida_alma_zamani { get; set; }
        public string vida_uflee_zamani { get; set; }
        public string sarjor_acik_sure { get; set; }
        public string sarjor_kapali_sure { get; set; }
        public string sarjor_besleme_set { get; set; }
        public string sikma_offset { get; set; }
        public string sikma_pos { get; set; }
        public string vida_besleme_deneme_tekrar { get; set; }
        public string vida_besleme_gecikme_sure { get; set; }
        public string kafa_1_aktif { get; set; }
        public string kafa_2_aktif { get; set; }
        public string vida_alma_total_hata_zaman { get; set; }
        public string vidalama_total_hata_zaman { get; set; }
        public string kafa_1_tool_offset { get; set; }
        public string kafa_2_tool_offset { get; set; }
        public string beyaz_bastan_vida_mesafe { get; set; }
        public string renkli_bastan_vida_mesafe { get; set; }
        public string beyaz_ara_vida_mesafe { get; set; }
        public string renkli_ara_vida_mesafe { get; set; }
        public string uzunluk { get; set; }
        public string profil_1 { get; set; }
        public string aci { get; set; }
        public string renk { get; set; }
        public string harici_poz { get; set; }
        public string vida_listesi { get; set; }
        public string beyaz { get; set; }
        public string renkli { get; set; }
        public string rpm { get; set; }
        public string profil_adi { get; set; }
        public string boy_yetersiz_faydali_parça_kullanilip_te { get; set; }
        public string boy_yetersiz { get; set; }
        public string etiket_fire_ofset { get; set; }
        public string parçayi_sil { get; set; }
        public string bu_profili_optimize_et { get; set; }
        public string tüm_profilleri_optimize_et { get; set; }
        public string kesildi_işaretle { get; set; }
        public string kesilmedi_işaretle { get; set; }
        public string axis25_ypc_profil_çikarma_unitesi { get; set; }
        public string freze_oncesi_arka_yan_baski_rulo_valfi { get; set; }
        public string fire_etiket_limiti { get; set; }
        public string prop_13gelişmiş_dörtgen { get; set; }
        public string prop_14arka_testere_strok { get; set; }
        public string prop_15üst_testere_strok { get; set; }
        public string vidalama_1 { get; set; }
        public string valarm0_acil_stop_alarmı { get; set; }
        public string valarm1_profil_sıkmalar_geride_sensor_al { get; set; }
        public string valarm17_profil_sıkmalar_yukarıda_sensor { get; set; }
        public string valarm2_vidalama_unitesi_piston_yukarıda { get; set; }
        public string valarm3_vidalama_unitesi_piston_yukarıda { get; set; }
        public string valarm4_home_yapılamadı { get; set; }
        public string valarm5_kafa_1_x_fault_alarm { get; set; }
        public string valarm6_kafa_1_y_fault_alarm { get; set; }
        public string valarm7_kafa_2_x_fault_alarm { get; set; }
        public string valarm8_kafa_2_y_fault_alarm { get; set; }
        public string valarm10_encoder_haberleşme_hatası { get; set; }
        public string valarm11_plc_haberleşme_hatası { get; set; }
        public string valarm12_motion_control_hatası { get; set; }
        public string valarm13_plc_command_error { get; set; }
        public string valarm14_carpışma_switch_hatası { get; set; }
        public string valarm15_kafa_1_vidalama_motor_piston_ha { get; set; }
        public string valarm16_kafa_2_vidalama_motor_piston_ha { get; set; }
        public string valarm20_iş_listesi_dolu { get; set; }
        public string valarm21_gelen_iş_profil_boyu_hatalı { get; set; }
        public string valarm22_job_sayısı_hatalı { get; set; }
        public string valarm23_kafa_1_z_fault_alarmı { get; set; }
        public string valarm24_kafa_2_z_fault_alarmı { get; set; }
        public string valarm25_kafa_1_z_delme_termik_alarm { get; set; }
        public string valarm26_kafa_2_z_delme_termik_alarm { get; set; }
        public string girisler { get; set; }
        public string cikislar { get; set; }
        public string start_butonu { get; set; }
        public string stop_butonu { get; set; }
        public string acil_stop { get; set; }
        public string carpışma_switch { get; set; }
        public string malzeme_sensoru { get; set; }
        public string vida_algılama_sensoru_kafa_1 { get; set; }
        public string vida_algılama_sensoru_kafa_2 { get; set; }
        public string profil_sıkmalar_yukarıda { get; set; }
        public string profil_sıkmalar_asagida { get; set; }
        public string profil_sıkmalar_geride { get; set; }
        public string kafa_1_vidalama_unitesi_piston_yukarıda { get; set; }
        public string kafa_2_vidalama_unitesi_piston_yukarıda { get; set; }
        public string kafa_1_motor_piston_asagida { get; set; }
        public string kafa_2_motor_piston_asagida { get; set; }
        public string konveyor_ileri_butonu { get; set; }
        public string konveyor_geri_butonu { get; set; }
        public string konveyor_termik { get; set; }
        public string matkap_termik_kafa_1 { get; set; }
        public string matkap_termik_kafa_2 { get; set; }
        public string sıkmalar_yukarı { get; set; }
        public string sıkma_1 { get; set; }
        public string sıkma_2 { get; set; }
        public string sıkma_3 { get; set; }
        public string sıkma_4 { get; set; }
        public string sıkma_5 { get; set; }
        public string sıkma_6 { get; set; }
        public string sıkma_7 { get; set; }
        public string sıkma_8 { get; set; }
        public string sıkma_9 { get; set; }
        public string sıkma_10 { get; set; }
        public string kafa_1_vidalama_unitesi_asagi { get; set; }
        public string kafa_1_vidalama_motoru_asagi { get; set; }
        public string kafa_1_vida_alma { get; set; }
        public string kafa_1_vida_kutusu { get; set; }
        public string kafa_1_vida_ufleme { get; set; }
        public string kafa_1_matkap_ufleme { get; set; }
        public string kafa_2_vidalama_unitesi_asagi { get; set; }
        public string kafa_2_vidalama_motoru_asagi { get; set; }
        public string kafa_2_vida_alma { get; set; }
        public string kafa_2_vida_kutusu { get; set; }
        public string kafa_2_vida_ufleme { get; set; }
        public string kafa_2_matkap_ufleme { get; set; }
        public string konveyor_ileri { get; set; }
        public string konveyor_geri { get; set; }
        public string kafa_1_delme_motoru { get; set; }
        public string kafa_2_delme_motoru { get; set; }
        public string vyedek { get; set; }
        public string vyedek_1 { get; set; }
        public string vyedek_2 { get; set; }
        public string vyedek_3 { get; set; }
        public string x_hiz { get; set; }
        public string x_acc_1 { get; set; }
        public string x_jerk_1 { get; set; }
        public string y_hiz_1 { get; set; }
        public string y_acc_1 { get; set; }
        public string y_jerk_1 { get; set; }
        public string z_hiz { get; set; }
        public string z_acc { get; set; }
        public string z_jerk { get; set; }
        public string tool_emniyet_mesafesi_1 { get; set; }
        public string tool_emniyet_mesafesi_delme { get; set; }
        public string kafa_1_min_x_pos_1 { get; set; }
        public string kafa_2_max_x_pos { get; set; }
        public string tool_offset_kafa_1_x { get; set; }
        public string tool_offset_kafa_1_y { get; set; }
        public string tool_offset_kafa_2_x { get; set; }
        public string tool_offset_kafa_2_y { get; set; }
        public string tool_offset_kafa_1_matkap_x { get; set; }
        public string tool_offset_kafa_1_matkap_y { get; set; }
        public string tool_offset_kafa_2_matkap_x { get; set; }
        public string tool_offset_kafa_2_matkap_y { get; set; }
        public string kafa_1_aktif_1 { get; set; }
        public string kafa_2_aktif_1 { get; set; }
        public string sikma_offset_1 { get; set; }
        public string sikma_pozisyon_1 { get; set; }
        public string sikma_pozisyon_2 { get; set; }
        public string sikma_pozisyon_3 { get; set; }
        public string sikma_pozisyon_4 { get; set; }
        public string sikma_pozisyon_5 { get; set; }
        public string sikma_pozisyon_6 { get; set; }
        public string sikma_pozisyon_7 { get; set; }
        public string sikma_pozisyon_8 { get; set; }
        public string sikma_pozisyon_9 { get; set; }
        public string sikma_pozisyon_10 { get; set; }
        public string profil_sensor_gecikme_1 { get; set; }
        public string profil_sikma_zamani_1 { get; set; }
        public string vida_alma_zamani_1 { get; set; }
        public string vida_basma_gecikme_zamani { get; set; }
        public string vida_ufleme_zamani { get; set; }
        public string şarjor_acilma_zamani { get; set; }
        public string şarjor_kapanma_zamani { get; set; }
        public string vida_alma_tot_hata_zamani { get; set; }
        public string vidalama_tot_hata_zamani { get; set; }
        public string sarjor_besleme_set_1 { get; set; }
        public string vida_besleme_max_deneme_sayisi { get; set; }
        public string başlangiç_mesafe_beyaz { get; set; }
        public string başlangiç_mesafe_renkli { get; set; }
        public string orta_mesafe_beyaz { get; set; }
        public string orta_mesafe_renkli { get; set; }
        public string kafa_1_x { get; set; }
        public string kafa_1_y { get; set; }
        public string kafa_2_x { get; set; }
        public string kafa_2_y { get; set; }
        public string kafa_1_z { get; set; }
        public string kafa_2_z { get; set; }
        public string aktuel_pos { get; set; }
        public string hedef_pos { get; set; }
        public string matkap_başlangiç_mesafe_beyaz { get; set; }
        public string matkap_başlangiç_mesafe_renkli { get; set; }
        public string matkap_orta_mesafe_beyaz { get; set; }
        public string matkap_orta_mesafe_renkli { get; set; }
        public string z_pozisyon_alt_kafa_1 { get; set; }
        public string z_pozisyon_alt_kafa_2 { get; set; }
        public string valarmyedek { get; set; }
        public string valarmyedek_1 { get; set; }
        public string valarmyedek_2 { get; set; }
        public string valarmyedek_3 { get; set; }
        public string valarmyedek_4 { get; set; }
        public string valarmyedek_5 { get; set; }
        public string valarmyedek_6 { get; set; }
        public string valarmyedek_7 { get; set; }
        public string yedek { get; set; }
        public string yedek_3 { get; set; }
        public string yedek_4 { get; set; }
        public string yedek_5 { get; set; }
        public string yedek_6 { get; set; }
        public string yedek_7 { get; set; }
        public string yedek_8 { get; set; }
        public string yedek_9 { get; set; }
        public string yedek_10 { get; set; }
        public string yedek_11 { get; set; }
        public string yedek_12 { get; set; }
        public string yedek_13 { get; set; }
        public string giriş_masasi_butonlar { get; set; }
        public string kabin_butonlar { get; set; }
        public string motorlar_butonlar { get; set; }
        public string giriş_çikiş { get; set; }
        public string giriş_üst_baski_1 { get; set; }
        public string giriş_üst_baski_2 { get; set; }
        public string giriş_üst_baski_3 { get; set; }
        public string giriş_üst_baski_ileri_1 { get; set; }
        public string giriş_üst_baski_ileri_2 { get; set; }
        public string giriş_üst_baski_ileri_3 { get; set; }
        public string giriş_yan_baski_1 { get; set; }
        public string giriş_yan_baski_2 { get; set; }
        public string giriş_yan_baski_3 { get; set; }
        public string giriş_yan_baski_4 { get; set; }
        public string giriş_yan_baski_5 { get; set; }
        public string giriş_yan_baski_6 { get; set; }
        public string giriş_yan_baski_7 { get; set; }
        public string giriş_yan_baski_8 { get; set; }
        public string giriş_yan_baski_yukari { get; set; }
        public string giriş_yan_baski_boşaltma_1 { get; set; }
        public string giriş_profil_tutma { get; set; }
        public string giriş_tork_dayama { get; set; }
        public string giriş_yan_sikmalar { get; set; }
        public string çikiş_profil_kaldirma_1 { get; set; }
        public string çikiş_profil_tutma_1 { get; set; }
        public string yukarida { get; set; }
        public string ileride { get; set; }
        public string aktif { get; set; }
        public string aşağida { get; set; }
        public string geride { get; set; }
        public string aşağida_1 { get; set; }
        public string pasif { get; set; }
        public string freze_öncesi_conta_baski_1 { get; set; }
        public string freze_öncesi_üst_yan_baski_1 { get; set; }
        public string freze_sonrasi_üst_yan_baski_1 { get; set; }
        public string freze_sonrasi_conta_baski { get; set; }
        public string testere_öncesi_üst_baski { get; set; }
        public string testere_öncesi_conta_baski_1 { get; set; }
        public string testere_sonrasi_üst_yan_baski { get; set; }
        public string testere_sonrasi_üst_baski_1 { get; set; }
        public string testere_sonrasi_alt_yan_baski { get; set; }
        public string testere_sonrasi_conta_baski { get; set; }
        public string freze_piston_1 { get; set; }
        public string freze_piston_2 { get; set; }
        public string freze_piston_3 { get; set; }
        public string freze_piston_4 { get; set; }
        public string freze_piston_5 { get; set; }
        public string freze_piston_6 { get; set; }
        public string freze_piston_7 { get; set; }
        public string freze_piston_8 { get; set; }
        public string freze_piston_9 { get; set; }
        public string üst_testere_45 { get; set; }
        public string üst_testere_90 { get; set; }
        public string alt_testere_135 { get; set; }
        public string testere_oncesi_yan_sikma { get; set; }
        public string giriş_konveyor { get; set; }
        public string freze_1_motor { get; set; }
        public string freze_2_motor { get; set; }
        public string freze_3_motor { get; set; }
        public string freze_4_motor { get; set; }
        public string freze_5_motor { get; set; }
        public string freze_6_motor { get; set; }
        public string freze_7_motor { get; set; }
        public string freze_8_motor { get; set; }
        public string freze_9_motor { get; set; }
        public string üst_testere_45_motor { get; set; }
        public string üst_testere_90_motor { get; set; }
        public string alt_testere_135_motor { get; set; }
        public string talas_konveyor_motor { get; set; }
        public string yağlama_motor { get; set; }
        public string çikiş_konveyor_motor { get; set; }
        public string kapi_switch { get; set; }
        public string çikiş_tur_sensoru { get; set; }
        public string çikiş_profil_sensoru { get; set; }
        public string çikiş_güvenlik { get; set; }
        public string giriş_güvenlik { get; set; }
        public string giriş_profil_sensoru { get; set; }
        public string hava_basinç_sensoru { get; set; }
        public string acil_stop_1 { get; set; }
        public string giriş_profil_lazer { get; set; }
        public string kirmizi_lamba { get; set; }
        public string yeşil_lamba { get; set; }
        public string stop_buton_lamba { get; set; }
        public string start_buton_lamba { get; set; }
        public string ust_testere_45_termik { get; set; }
        public string üst_testere_90_termik { get; set; }
        public string alt_testere_135_termik { get; set; }
        public string start_butonu_1 { get; set; }
        public string stop_butonu_1 { get; set; }
        public string çikiş_konveyoru_termik { get; set; }
        public string talaş_konveyoru_termik { get; set; }
        public string giriş_konveyoru_termik { get; set; }
        public string giriş_konveyor_start_butonu { get; set; }
        public string kafes_güvenlik_switch { get; set; }
        public string giriş_acil_stop { get; set; }
        public string joistik_x_ileri { get; set; }
        public string joistik_x_geri { get; set; }
        public string joistik_y_ileri { get; set; }
        public string joistik_y_geri { get; set; }
        public string kabin_hava_üfleme { get; set; }
        public string aktif_1 { get; set; }
        public string pasif_1 { get; set; }
        public string yedek_14 { get; set; }
        public string yedek_15 { get; set; }
        public string yedek_16 { get; set; }
        public string yedek_17 { get; set; }
        public string yedek_18 { get; set; }
        public string yedek_19 { get; set; }
        public string yedek_20 { get; set; }
        public string yedek_21 { get; set; }
        public string yedek_22 { get; set; }
        public string yedek_23 { get; set; }
        public string yedek_24 { get; set; }
        public string yedek_25 { get; set; }
        public string yedek_26 { get; set; }
        public string yedek_27 { get; set; }
        public string yedek_28 { get; set; }
        public string yedek_29 { get; set; }
        public string yedek_30 { get; set; }
        public string yedek_31 { get; set; }
        public string yedek_32 { get; set; }
        public string yedek_33 { get; set; }
        public string yedek_34 { get; set; }
        public string yedek_35 { get; set; }
        public string yedek_36 { get; set; }
        public string yedek_37 { get; set; }
        public string yedek_38 { get; set; }
        public string yedek_39 { get; set; }
        public string yedek_40 { get; set; }
        public string yedek_41 { get; set; }
        public string yedek_42 { get; set; }
        public string yedek_43 { get; set; }
        public string yedek_44 { get; set; }
        public string yedek_45 { get; set; }
        public string yedek_46 { get; set; }
        public string yedek_47 { get; set; }
        public string yedek_48 { get; set; }
        public string yedek_49 { get; set; }
        public string yedek_50 { get; set; }
        public string yedek_51 { get; set; }
        public string yedek_52 { get; set; }
        public string yedek_53 { get; set; }
        public string yedek_54 { get; set; }
        public string yedek_55 { get; set; }
        public string yedek_56 { get; set; }
        public string yedek_57 { get; set; }
        public string yedek_58 { get; set; }
        public string yedek_59 { get; set; }
        public string yedek_60 { get; set; }
        public string yedek_61 { get; set; }
        public string yedek_62 { get; set; }
        public string yedek_63 { get; set; }
        public string yedek_64 { get; set; }
        public string yedek_65 { get; set; }
        public string yedek_66 { get; set; }
        public string yedek_67 { get; set; }
        public string yedek_68 { get; set; }
        public string yedek_69 { get; set; }
        public string yedek_70 { get; set; }
        public string yedek_71 { get; set; }
        public string yedek_72 { get; set; }
        public string yedek_73 { get; set; }
        public string yedek_74 { get; set; }
        public string yedek_75 { get; set; }
        public string yedek_76 { get; set; }
        public string yedek_77 { get; set; }
        public string yedek_78 { get; set; }
        public string yedek_79 { get; set; }
        public string yedek_80 { get; set; }
        public string yedek_81 { get; set; }
        public string yedek_82 { get; set; }
        public string yedek_83 { get; set; }
        public string yedek_84 { get; set; }
        public string yedek_85 { get; set; }
        public string yedek_86 { get; set; }
        public string yedek_87 { get; set; }
        public string yedek_88 { get; set; }
        public string yedek_89 { get; set; }
        public string yedek_90 { get; set; }
        public string yedek_91 { get; set; }
        public string yedek_92 { get; set; }
        public string yedek_93 { get; set; }
        public string yedek_94 { get; set; }
        public string yedek_95 { get; set; }
        public string yedek_96 { get; set; }
        public string yedek_97 { get; set; }
        public string yedek_98 { get; set; }
        public string yedek_99 { get; set; }
        public string yedek_100 { get; set; }
        public string yedek_101 { get; set; }
        public string yedek_102 { get; set; }
        public string yedek_103 { get; set; }
        public string yedek_104 { get; set; }
        public string yedek_105 { get; set; }
        public string yedek_106 { get; set; }
        public string yedek_107 { get; set; }
        public string yedek_108 { get; set; }
        public string yedek_109 { get; set; }
        public string yedek_110 { get; set; }
        public string yedek_111 { get; set; }
        public string yedek_112 { get; set; }
        public string yedek_113 { get; set; }
        public string yedek_114 { get; set; }
        public string yedek_115 { get; set; }
        public string yedek_116 { get; set; }
        public string yedek_117 { get; set; }
        public string yedek_118 { get; set; }
        public string yedek_119 { get; set; }
        public string yedek_120 { get; set; }
        public string yedek_121 { get; set; }
        public string yedek_122 { get; set; }
        public string yedek_123 { get; set; }
        public string yedek_124 { get; set; }
        public string yedek_125 { get; set; }
        public string yedek_126 { get; set; }
        public string yedek_127 { get; set; }
        public string yedek_128 { get; set; }
        public string yedek_129 { get; set; }
        public string yedek_130 { get; set; }
        public string yedek_131 { get; set; }
        public string yedek_132 { get; set; }
        public string yedek_133 { get; set; }
        public string yedek_134 { get; set; }
        public string yedek_135 { get; set; }
        public string yedek_136 { get; set; }
        public string yedek_137 { get; set; }
        public string yedek_138 { get; set; }
        public string yedek_139 { get; set; }
        public string yedek_140 { get; set; }
        public string yedek_141 { get; set; }
        public string yedek_142 { get; set; }
        public string yedek_143 { get; set; }
        public string yedek_144 { get; set; }
        public string yedek_145 { get; set; }
        public string yedek_146 { get; set; }
        public string yedek_147 { get; set; }
        public string yedek_148 { get; set; }
        public string yedek_149 { get; set; }
        public string yedek_150 { get; set; }
        public string yedek_151 { get; set; }
        public string yedek_152 { get; set; }
        public string yedek_153 { get; set; }
        public string yedek_154 { get; set; }
        public string yedek_155 { get; set; }
        public string yedek_156 { get; set; }
        public string yedek_157 { get; set; }
        public string yedek_158 { get; set; }
        public string yedek_159 { get; set; }
        public string yedek_160 { get; set; }
        public string yedek_161 { get; set; }
        public string yedek_162 { get; set; }
        public string yedek_163 { get; set; }
        public string yedek_164 { get; set; }
        public string yedek_165 { get; set; }
        public string yedek_166 { get; set; }
        public string yedek_167 { get; set; }
        public string yedek_168 { get; set; }
        public string yedek_169 { get; set; }
        public string yedek_170 { get; set; }
        public string yedek_171 { get; set; }
        public string yedek_172 { get; set; }
        public string yedek_173 { get; set; }
        public string yedek_174 { get; set; }
        public string yedek_175 { get; set; }
        public string yedek_176 { get; set; }
        public string yedek_177 { get; set; }
        public string yedek_178 { get; set; }
        public string yedek_179 { get; set; }
        public string yedek_180 { get; set; }
        public string yedek_181 { get; set; }
        public string yedek_182 { get; set; }
        public string yedek_183 { get; set; }
        public string yedek_184 { get; set; }
        public string yedek_185 { get; set; }
        public string yedek_186 { get; set; }
        public string yedek_187 { get; set; }
        public string yedek_188 { get; set; }
        public string yedek_189 { get; set; }
        public string yedek_190 { get; set; }
        public string yedek_191 { get; set; }
        public string yedek_192 { get; set; }
        public string yedek_193 { get; set; }
        public string yedek_194 { get; set; }
        public string yedek_195 { get; set; }
        public string yedek_196 { get; set; }
        public string yedek_197 { get; set; }
        public string yedek_198 { get; set; }
        public string yedek_199 { get; set; }
        public string yedek_200 { get; set; }
        public string yedek_201 { get; set; }
        public string yedek_202 { get; set; }
        public string yedek_203 { get; set; }
        public string yedek_204 { get; set; }
        public string yedek_205 { get; set; }
        public string yedek_206 { get; set; }
        public string yedek_207 { get; set; }
        public string yedek_208 { get; set; }
        public string yedek_209 { get; set; }
        public string yedek_210 { get; set; }
        public string yedek_211 { get; set; }
        public string yedek_212 { get; set; }
        public string yedek_213 { get; set; }
        public string yedek_214 { get; set; }
        public string yedek_215 { get; set; }
        public string yedek_216 { get; set; }
        public string yedek_217 { get; set; }
        public string yedek_218 { get; set; }
        public string yedek_219 { get; set; }
        public string yedek_220 { get; set; }
        public string yedek_221 { get; set; }
        public string yedek_222 { get; set; }
        public string yedek_223 { get; set; }
        public string yedek_224 { get; set; }
        public string yedek_225 { get; set; }
        public string yedek_226 { get; set; }
        public string yedek_227 { get; set; }
        public string yedek_228 { get; set; }
        public string yedek_229 { get; set; }
        public string yedek_230 { get; set; }
        public string yedek_231 { get; set; }
        public string yedek_232 { get; set; }
        public string yedek_233 { get; set; }
        public string yedek_234 { get; set; }
        public string yedek_235 { get; set; }
        public string yedek_236 { get; set; }
        public string yedek_237 { get; set; }
        public string yedek_238 { get; set; }
        public string yedek_239 { get; set; }
        public string yedek_240 { get; set; }
        public string yedek_241 { get; set; }
        public string yedek_242 { get; set; }
        public string yedek_243 { get; set; }
        public string yedek_244 { get; set; }
        public string yedek_245 { get; set; }
        public string yedek_246 { get; set; }
        public string yedek_247 { get; set; }
        public string yedek_248 { get; set; }
        public string yedek_249 { get; set; }
        public string yedek_250 { get; set; }
        public string yedek_251 { get; set; }
        public string yedek_252 { get; set; }
        public string yedek_253 { get; set; }
        public string yedek_254 { get; set; }
        public string yedek_255 { get; set; }
        public string yedek_256 { get; set; }
        public string yedek_257 { get; set; }
        public string yedek_258 { get; set; }
        public string yedek_259 { get; set; }
        public string yedek_260 { get; set; }
        public string yedek_261 { get; set; }
        public string yedek_262 { get; set; }
        public string yedek_263 { get; set; }
        public string yedek_264 { get; set; }
        public string yedek_265 { get; set; }
        public string yedek_266 { get; set; }
        public string yedek_267 { get; set; }
        public string yedek_268 { get; set; }
        public string yedek_269 { get; set; }
        public string yedek_270 { get; set; }
        public string yedek_271 { get; set; }
        public string yedek_272 { get; set; }
        public string yedek_273 { get; set; }
        public string yedek_274 { get; set; }
        public string yedek_275 { get; set; }
        public string yedek_276 { get; set; }
        public string yedek_277 { get; set; }
        public string yedek_278 { get; set; }
        public string yedek_279 { get; set; }
        public string yedek_280 { get; set; }
        public string yedek_281 { get; set; }
        public string yedek_282 { get; set; }
        public string yedek_283 { get; set; }
        public string yedek_284 { get; set; }
        public string yedek_285 { get; set; }
        public string yedek_286 { get; set; }
        public string yedek_287 { get; set; }
        public string yedek_288 { get; set; }
        public string yedek_289 { get; set; }
        public string yedek_290 { get; set; }
        public string yedek_291 { get; set; }
        public string yedek_292 { get; set; }
        public string yedek_293 { get; set; }
        public string yedek_294 { get; set; }
        public string yedek_295 { get; set; }
        public string yedek_296 { get; set; }
        public string yedek_297 { get; set; }
        public string yedek_298 { get; set; }
        public string yedek_299 { get; set; }
        public string yedek_300 { get; set; }
        public string yedek_301 { get; set; }
        public string yedek_302 { get; set; }
        public string yedek_303 { get; set; }
        public string yedek_304 { get; set; }
        public string yedek_305 { get; set; }
        public string yedek_306 { get; set; }
        public string yedek_307 { get; set; }
        public string yedek_308 { get; set; }
        public string yedek_309 { get; set; }
        public string yedek_310 { get; set; }
        public string yedek_311 { get; set; }
        public string yedek_312 { get; set; }
        public string yedek_313 { get; set; }
        public string yedek_314 { get; set; }
        public string yedek_315 { get; set; }
        public string yedek_316 { get; set; }
        public string yedek_317 { get; set; }
        public string yedek_318 { get; set; }
        public string yedek_319 { get; set; }
        public string yedek_320 { get; set; }
        public string yedek_321 { get; set; }
        public string yedek_322 { get; set; }
        public string yedek_323 { get; set; }
        public string yedek_324 { get; set; }
        public string yedek_325 { get; set; }
        public string yedek_326 { get; set; }
        public string yedek_327 { get; set; }
        public string yedek_328 { get; set; }
        public string yedek_329 { get; set; }
        public string yedek_330 { get; set; }
        public string yedek_331 { get; set; }
        public string yedek_332 { get; set; }
        public string yedek_333 { get; set; }
        public string yedek_334 { get; set; }
        public string yedek_335 { get; set; }
        public string yedek_336 { get; set; }
        public string yedek_337 { get; set; }
        public string yedek_338 { get; set; }
        public string yedek_339 { get; set; }
        public string yedek_340 { get; set; }
        public string yedek_341 { get; set; }
        public string yedek_342 { get; set; }
        public string yedek_343 { get; set; }
        public string yedek_344 { get; set; }
        public string yedek_345 { get; set; }
        public string yedek_346 { get; set; }
        public string yedek_347 { get; set; }
        public string yedek_348 { get; set; }
        public string yedek_349 { get; set; }
        public string yedek_350 { get; set; }
        public string yedek_351 { get; set; }
        public string yedek_352 { get; set; }
        public string yedek_353 { get; set; }
        public string yedek_354 { get; set; }
        public string yedek_355 { get; set; }
        public string yedek_356 { get; set; }
        public string yedek_357 { get; set; }
        public string yedek_358 { get; set; }
        public string yedek_359 { get; set; }
        public string yedek_360 { get; set; }
        public string yedek_361 { get; set; }
        public string yedek_362 { get; set; }
        public string yedek_363 { get; set; }
        public string yedek_364 { get; set; }
        public string yedek_365 { get; set; }
        public string yedek_366 { get; set; }
        public string yedek_367 { get; set; }
        public string yedek_368 { get; set; }
        public string yedek_369 { get; set; }
        public string yedek_370 { get; set; }
        public string yedek_371 { get; set; }
        public string yedek_372 { get; set; }
        public string yedek_373 { get; set; }
        public string yedek_374 { get; set; }
        public string yedek_375 { get; set; }
        public string yedek_376 { get; set; }
        public string yedek_377 { get; set; }
        public string yedek_378 { get; set; }
        public string yedek_379 { get; set; }
        public string yedek_380 { get; set; }
        public string yedek_381 { get; set; }
        public string yedek_382 { get; set; }
        public string yedek_383 { get; set; }
        public string yedek_384 { get; set; }
        public string yedek_385 { get; set; }
        public string yedek_386 { get; set; }
        public string yedek_387 { get; set; }
        public string yedek_388 { get; set; }
        public string yedek_389 { get; set; }
        public string yedek_390 { get; set; }
        public string yedek_391 { get; set; }
        public string yedek_392 { get; set; }
        public string yedek_393 { get; set; }
        public string yedek_394 { get; set; }
        public string yedek_395 { get; set; }
        public string yedek_396 { get; set; }
        public string yedek_397 { get; set; }
        public string yedek_398 { get; set; }
        public string yedek_399 { get; set; }
        public string yedek_400 { get; set; }
        public string yedek_401 { get; set; }
        public string yedek_402 { get; set; }
        public string yedek_403 { get; set; }
        public string yedek_404 { get; set; }
        public string yedek_405 { get; set; }
        public string yedek_406 { get; set; }
        public string yedek_407 { get; set; }
        public string yedek_408 { get; set; }
        public string yedek_409 { get; set; }
        public string yedek_410 { get; set; }
        public string yedek_411 { get; set; }
        public string yedek_412 { get; set; }
        public string yedek_413 { get; set; }
        public string yedek_414 { get; set; }
        public string yedek_415 { get; set; }
        public string yedek_416 { get; set; }
        public string yedek_417 { get; set; }
        public string yedek_418 { get; set; }
        public string yedek_419 { get; set; }
        public string yedek_420 { get; set; }
        public string yedek_421 { get; set; }
        public string yedek_422 { get; set; }
        public string yedek_423 { get; set; }
        public string yedek_424 { get; set; }
        public string yedek_425 { get; set; }
        public string yedek_426 { get; set; }
        public string yedek_427 { get; set; }
        public string yedek_428 { get; set; }
        public string yedek_429 { get; set; }
        public string yedek_430 { get; set; }
        public string yedek_431 { get; set; }
        public string yedek_432 { get; set; }
        public string yedek_433 { get; set; }
        public string yedek_434 { get; set; }
        public string yedek_435 { get; set; }
        public string yedek_436 { get; set; }
        public string yedek_437 { get; set; }
        public string yedek_438 { get; set; }
        public string yedek_439 { get; set; }
        public string yedek_440 { get; set; }
        public string yedek_441 { get; set; }
        public string yedek_442 { get; set; }
        public string yedek_443 { get; set; }
        public string yedek_444 { get; set; }
        public string yedek_445 { get; set; }
        public string yedek_446 { get; set; }
        public string yedek_447 { get; set; }
        public string yedek_448 { get; set; }
        public string yedek_449 { get; set; }
        public string yedek_450 { get; set; }
        public string yedek_451 { get; set; }
        public string yedek_452 { get; set; }
        public string yedek_453 { get; set; }
        public string yedek_454 { get; set; }
        public string yedek_455 { get; set; }
        public string yedek_456 { get; set; }
        public string yedek_457 { get; set; }
        public string yedek_458 { get; set; }
        public string yedek_459 { get; set; }
        public string yedek_460 { get; set; }
        public string yedek_461 { get; set; }
        public string yedek_462 { get; set; }
        public string yedek_463 { get; set; }
        public string yedek_464 { get; set; }
        public string yedek_465 { get; set; }
        public string yedek_466 { get; set; }
        public string yedek_467 { get; set; }
        public string yedek_468 { get; set; }
        public string yedek_469 { get; set; }
        public string yedek_470 { get; set; }
        public string yedek_471 { get; set; }
        public string yedek_472 { get; set; }
        public string yedek_473 { get; set; }
        public string yedek_474 { get; set; }
        public string yedek_475 { get; set; }
        public string yedek_476 { get; set; }
        public string yedek_477 { get; set; }
        public string yedek_478 { get; set; }
        public string yedek_479 { get; set; }
        public string yedek_480 { get; set; }
        public string yedek_481 { get; set; }
        public string yedek_482 { get; set; }
        public string yedek_483 { get; set; }
        public string yedek_484 { get; set; }
        public string yedek_485 { get; set; }
        public string yedek_486 { get; set; }
        public string yedek_487 { get; set; }
        public string yedek_488 { get; set; }
        public string yedek_489 { get; set; }
        public string yedek_490 { get; set; }
        public string yedek_491 { get; set; }
        public string yedek_492 { get; set; }
        public string yedek_493 { get; set; }
        public string yedek_494 { get; set; }
        public string yedek_495 { get; set; }
        public string yedek_496 { get; set; }
        public string yedek_497 { get; set; }
        public string yedek_498 { get; set; }
        public string yedek_499 { get; set; }
        public string yedek_500 { get; set; }
        public string yedek_501 { get; set; }
        public string yedek_502 { get; set; }
        public string yedek_503 { get; set; }
        public string yedek_504 { get; set; }
        public string yedek_505 { get; set; }
        public string yedek_506 { get; set; }
        public string yedek_507 { get; set; }
        public string yedek_508 { get; set; }
    }
}